services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manage-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - vendor-data:/var/www/vendor
    ports:
      - "8000:80"
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    container_name: manage-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel-manage
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: manage-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog
    container_name: manage-mailhog
    ports:
      - "8025:8025"

volumes:
  vendor-data:
  db-data: